function menuFunc() {
  document.getElementById('responsive-menu').style.transform = "translateX(0)";
  document.getElementById('responsive-menu-bg').style.transform = "translateX(0)";
  document.getElementById('toggle-top').style.transform = "rotateZ(50deg)";
  document.getElementById('toggle-mid').style.width= "0";
  document.getElementById('toggle-bot').style.transform = "rotateZ(-50deg)";
  document.getElementById('toggle-bot').style.top = "20px";
  document.getElementById('toggle-top').style.top = "20px";
}
function menuFuncX() {
  document.getElementById('responsive-menu').style.transform = "translateX(-110%)";
  document.getElementById('responsive-menu-bg').style.transform = "translateX(-110%)";
  document.getElementById('toggle-bot').style.top = "28px";
  document.getElementById('toggle-top').style.top = "8px";
  document.getElementById('toggle-bot').style.transform = "rotateZ(0deg)";
  document.getElementById('toggle-top').style.transform = "rotateZ(0deg)";
  document.getElementById('toggle-mid').style.width = "35px";
}
function slideFunc() {
  document.getElementById('slide-bar-2').style.transform = "translateX(0)";
  document.getElementById('slide-bar-1').style.transform = "translateX(100%)";
  document.getElementById('circle-1').style.background = "#0fb78d";
  document.getElementById('circle-2').style.background = "white";
}
function slideFunc_2() {
  document.getElementById('slide-bar-2').style.transform = "translateX(-100%)";
  document.getElementById('slide-bar-1').style.transform = "translateX(0)";
  document.getElementById('circle-1').style.background = "white";
  document.getElementById('circle-2').style.background = "#0fb78d";
}
let nav = document.getElementById('nav');
let menuInfo0 = document.getElementById('navLink0');
let menuInfo = document.getElementById('navLink');
let menuInfo1 = document.getElementById('navLink1');
let menuInfo2 = document.getElementById('navLink2');
let menuInfo3 = document.getElementById('navLink3');
let menuInfo4 = document.getElementById('navLink4');
let menuInfo5 = document.getElementById('navLink5');

window.onscroll = function() {
  if(window.pageYOffset > 50) {
    nav.style.background = "#FFFFFFE8";
    nav.style.boxShadow = "0 0px 5px rgba(0, 0, 0, .131)";
    menuInfo0.classList.add ("active2");
    menuInfo.classList.add ("scrollMenu");
    menuInfo1.classList.add ("scrollMenu");
    menuInfo2.classList.add ("scrollMenu");
    menuInfo3.classList.add ("scrollMenu");
    menuInfo4.classList.add ("scrollMenu");
    menuInfo5.classList.add ("scrollMenu");
  }
  else {
    nav.style.background = "transparent";
    nav.style.boxShadow = "none";
    menuInfo0.classList.remove ("active2");
    menuInfo.classList.remove ("scrollMenu");
    menuInfo1.classList.remove ("scrollMenu");
    menuInfo2.classList.remove ("scrollMenu");
    menuInfo3.classList.remove ("scrollMenu");
    menuInfo4.classList.remove ("scrollMenu");
    menuInfo5.classList.remove ("scrollMenu");
  }
}
$('.autoplay').slick({
    slidesToShow: 3,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 1000,

});
let x = 0;
function settingFunc() {
    if(x==0) {
      document.getElementById('setting').style.left ="0";
      x+=1;
    }
    else if(x==1) {
      document.getElementById('setting').style.left ="-250px";
      x-=1;
    } 
}

function fontFunc1() {
  document.querySelector('.font-1').classList.add("font-active");
  document.querySelector('.font-2').classList.remove("font-active");
  document.querySelector('.font-3').classList.remove("font-active");
  document.querySelector('.font-4').classList.remove("font-active");
  document.querySelector('.font-5').classList.remove("font-active");
  document.querySelector(".nav-link1").style.fontSize = "9px" ;
  document.querySelector(".nav-link2").style.fontSize = "9px" ;
  document.querySelector(".nav-link3").style.fontSize = "9px" ;
  document.querySelector(".nav-link4").style.fontSize = "9px" ;
  document.querySelector(".nav-link5").style.fontSize = "9px" ;
  document.querySelector(".nav-link6").style.fontSize = "9px" ;
  document.querySelector(".nav-link7").style.fontSize = "9px" ;
  document.getElementById("slidename").style.fontSize = "42px";
  document.querySelector(".slide_2").style.fontSize = "42px";
  document.getElementById("button").style.fontSize = "9px";
  document.querySelector(".button_2").style.fontSize = "9px";
  document.querySelector(".icon1").style.fontSize= "19px";
  document.querySelector(".icon2").style.fontSize= "19px";
  document.querySelector(".icon3").style.fontSize= "19px";
  document.querySelector(".service-theme1").style.fontSize = "10px";
  document.querySelector(".service-theme2").style.fontSize = "10px";
  document.querySelector(".service-theme3").style.fontSize = "10px";
  document.querySelector(".service-p1").style.fontSize = "14px";
  document.querySelector(".service-p2").style.fontSize = "14px";
  document.querySelector(".service-p3").style.fontSize = "14px";
  document.querySelector(".sale1").style.fontSize = "8px";
  document.querySelector(".sale2").style.fontSize = "8px";
  document.querySelector(".sale3").style.fontSize = "8px";
  document.querySelector(".sale4").style.fontSize = "8px";
  document.querySelector(".ptheme1").style.fontSize = "13px";
  document.querySelector(".ptheme2").style.fontSize = "13px";
  document.querySelector(".ptheme3").style.fontSize = "13px";
  document.querySelector(".ptheme4").style.fontSize = "13px";
  document.querySelector(".ptheme5").style.fontSize = "13px";
  document.querySelector(".ptheme6").style.fontSize = "13px";
  document.querySelector(".price1").style.fontSize = "11px";
  document.querySelector(".price2").style.fontSize = "11px";
  document.querySelector(".price3").style.fontSize = "11px";
  document.querySelector(".price4").style.fontSize = "11px";
  document.querySelector(".price5").style.fontSize = "11px";
  document.querySelector(".price6").style.fontSize = "11px";
  document.querySelector(".dealtheme").style.fontSize = "14px";
  document.querySelector(".deal1").style.fontSize = "28px";
  document.querySelector(".dealp").style.fontSize = "14px";
  document.querySelector(".deala").style.fontSize = "9px";
  document.querySelector(".h3").style.fontSize = "26px";
  document.querySelector(".slick-next").style.fontSize = "14px";
  document.querySelector(".slick-prev ").style.fontSize = "14px";
  document.querySelector(".new1").style.fontSize = "8px";
  document.querySelector(".new2").style.fontSize = "8px";
  document.querySelector(".new3").style.fontSize = "8px";
  document.querySelector(".new4").style.fontSize = "8px";
  document.querySelector(".popular1").style.fontSize = "13px";
  document.querySelector(".popular2").style.fontSize = "13px";
  document.querySelector(".popular3").style.fontSize = "13px";
  document.querySelector(".popular4").style.fontSize = "13px";
  document.querySelector(".popular5").style.fontSize = "13px";
  document.querySelector(".popular6").style.fontSize = "13px";
  document.querySelector(".pop1").style.fontSize = "11px";
  document.querySelector(".pop2").style.fontSize = "11px";
  document.querySelector(".pop3").style.fontSize = "11px";
  document.querySelector(".pop4").style.fontSize = "11px";
  document.querySelector(".pop5").style.fontSize = "11px";
  document.querySelector(".pop6").style.fontSize = "11px";
  document.querySelector(".head1").style.fontSize = "18px";
  document.querySelector(".head2").style.fontSize = "18px";
  document.querySelector(".head3").style.fontSize = "18px";
  document.querySelector(".head4").style.fontSize = "18px";
  document.querySelector(".a1").style.fontSize = "14px";
  document.querySelector(".a2").style.fontSize = "14px";
  document.querySelector(".a3").style.fontSize = "14px";
  document.querySelector(".a4").style.fontSize = "14px";
  document.querySelector(".a5").style.fontSize = "14px";
  document.querySelector(".a6").style.fontSize = "14px";
  document.querySelector(".a7").style.fontSize = "14px";
  document.querySelector(".a8").style.fontSize = "14px";
  document.querySelector(".a9").style.fontSize = "14px";
  document.querySelector(".a10").style.fontSize = "14px";
  document.querySelector(".a11").style.fontSize = "14px";
  document.querySelector(".a12").style.fontSize = "14px";
  document.querySelector(".a13").style.fontSize = "14px";
  document.querySelector(".copy").style.fontSize = "14px";
}
function fontFunc2() {
  document.querySelector('.font-1').classList.remove("font-active");
  document.querySelector('.font-2').classList.add("font-active");
  document.querySelector('.font-3').classList.remove("font-active");
  document.querySelector('.font-4').classList.remove("font-active");
  document.querySelector('.font-5').classList.remove("font-active");
  document.querySelector(".nav-link1").style.fontSize = "10px" ;
  document.querySelector(".nav-link2").style.fontSize = "10px" ;
  document.querySelector(".nav-link3").style.fontSize = "10px" ;
  document.querySelector(".nav-link4").style.fontSize = "10px" ;
  document.querySelector(".nav-link5").style.fontSize = "10px" ;
  document.querySelector(".nav-link6").style.fontSize = "10px" ;
  document.querySelector(".nav-link7").style.fontSize = "10px" ;
  document.getElementById("slidename").style.fontSize = "46px";
  document.querySelector(".slide_2").style.fontSize = "46px";
  document.getElementById("button").style.fontSize = "10px";
  document.querySelector(".button_2").style.fontSize = "10px";
  document.querySelector(".icon1").style.fontSize= "22px";
  document.querySelector(".icon2").style.fontSize= "22px";
  document.querySelector(".icon3").style.fontSize= "22px";
  document.querySelector(".service-theme1").style.fontSize = "11px";
  document.querySelector(".service-theme2").style.fontSize = "11px";
  document.querySelector(".service-theme3").style.fontSize = "11px";
  document.querySelector(".service-p1").style.fontSize = "15px";
  document.querySelector(".service-p2").style.fontSize = "15px";
  document.querySelector(".service-p3").style.fontSize = "15px";
  document.querySelector(".sale1").style.fontSize = "9px";
  document.querySelector(".sale2").style.fontSize = "9px";
  document.querySelector(".sale3").style.fontSize = "9px";
  document.querySelector(".sale4").style.fontSize = "9px";
  document.querySelector(".ptheme1").style.fontSize = "14px";
  document.querySelector(".ptheme2").style.fontSize = "14px";
  document.querySelector(".ptheme3").style.fontSize = "14px";
  document.querySelector(".ptheme4").style.fontSize = "14px";
  document.querySelector(".ptheme5").style.fontSize = "14px";
  document.querySelector(".ptheme6").style.fontSize = "14px";
  document.querySelector(".price1").style.fontSize = "12px";
  document.querySelector(".price2").style.fontSize = "12px";
  document.querySelector(".price3").style.fontSize = "12px";
  document.querySelector(".price4").style.fontSize = "12px";
  document.querySelector(".price5").style.fontSize = "12px";
  document.querySelector(".price6").style.fontSize = "12px";
  document.querySelector(".dealtheme").style.fontSize = "15px";
  document.querySelector(".deal1").style.fontSize = "30px";
  document.querySelector(".dealp").style.fontSize = "15px";
  document.querySelector(".deala").style.fontSize = "10px";
  document.querySelector(".h3").style.fontSize = "27px";
  document.querySelector(".slick-next").style.fontSize = "15px";
  document.querySelector(".slick-prev ").style.fontSize = "15px";
  document.querySelector(".new1").style.fontSize = "9px";
  document.querySelector(".new2").style.fontSize = "9px";
  document.querySelector(".new3").style.fontSize = "9px";
  document.querySelector(".new4").style.fontSize = "9px";
  document.querySelector(".popular1").style.fontSize = "14px";
  document.querySelector(".popular2").style.fontSize = "14px";
  document.querySelector(".popular3").style.fontSize = "14px";
  document.querySelector(".popular4").style.fontSize = "14px";
  document.querySelector(".popular5").style.fontSize = "14px";
  document.querySelector(".popular6").style.fontSize = "14px";
  document.querySelector(".pop1").style.fontSize = "12px";
  document.querySelector(".pop2").style.fontSize = "12px";
  document.querySelector(".pop3").style.fontSize = "12px";
  document.querySelector(".pop4").style.fontSize = "12px";
  document.querySelector(".pop5").style.fontSize = "12px";
  document.querySelector(".pop6").style.fontSize = "12px";
  document.querySelector(".head1").style.fontSize = "19px";
  document.querySelector(".head2").style.fontSize = "19px";
  document.querySelector(".head3").style.fontSize = "19px";
  document.querySelector(".head4").style.fontSize = "19px";
  document.querySelector(".a1").style.fontSize = "15px";
  document.querySelector(".a2").style.fontSize = "15px";
  document.querySelector(".a3").style.fontSize = "15px";
  document.querySelector(".a4").style.fontSize = "15px";
  document.querySelector(".a5").style.fontSize = "15px";
  document.querySelector(".a6").style.fontSize = "15px";
  document.querySelector(".a7").style.fontSize = "15px";
  document.querySelector(".a8").style.fontSize = "15px";
  document.querySelector(".a9").style.fontSize = "15px";
  document.querySelector(".a10").style.fontSize = "15px";
  document.querySelector(".a11").style.fontSize = "15px";
  document.querySelector(".a12").style.fontSize = "15px";
  document.querySelector(".a13").style.fontSize = "15px";
  document.querySelector(".copy").style.fontSize = "15px";
}
function fontFunc3() {
  document.querySelector('.font-1').classList.remove("font-active");
  document.querySelector('.font-2').classList.remove("font-active");
  document.querySelector('.font-3').classList.add("font-active");
  document.querySelector('.font-4').classList.remove("font-active");
  document.querySelector('.font-5').classList.remove("font-active");
  document.querySelector(".nav-link1").style.fontSize = "11px" ;
  document.querySelector(".nav-link2").style.fontSize = "11px" ;
  document.querySelector(".nav-link3").style.fontSize = "11px" ;
  document.querySelector(".nav-link4").style.fontSize = "11px" ;
  document.querySelector(".nav-link5").style.fontSize = "11px" ;
  document.querySelector(".nav-link6").style.fontSize = "11px" ;
  document.querySelector(".nav-link7").style.fontSize = "11px" ;
  document.getElementById("slidename").style.fontSize = "50px";
  document.querySelector(".slide_2").style.fontSize = "50px";
  document.getElementById("button").style.fontSize = "11px";
  document.querySelector(".button_2").style.fontSize = "11px";
  document.querySelector(".icon1").style.fontSize= "25px";
  document.querySelector(".icon2").style.fontSize= "25px";
  document.querySelector(".icon3").style.fontSize= "25px";
  document.querySelector(".service-theme1").style.fontSize = "12px";
  document.querySelector(".service-theme2").style.fontSize = "12px";
  document.querySelector(".service-theme3").style.fontSize = "12px";
  document.querySelector(".service-p1").style.fontSize = "16px";
  document.querySelector(".service-p2").style.fontSize = "16px";
  document.querySelector(".service-p3").style.fontSize = "16px";
  document.querySelector(".sale1").style.fontSize = "10px";
  document.querySelector(".sale2").style.fontSize = "10px";
  document.querySelector(".sale3").style.fontSize = "10px";
  document.querySelector(".sale4").style.fontSize = "10px";
  document.querySelector(".ptheme1").style.fontSize = "15px";
  document.querySelector(".ptheme2").style.fontSize = "15px";
  document.querySelector(".ptheme3").style.fontSize = "15px";
  document.querySelector(".ptheme4").style.fontSize = "15px";
  document.querySelector(".ptheme5").style.fontSize = "15px";
  document.querySelector(".ptheme6").style.fontSize = "15px";
  document.querySelector(".price1").style.fontSize = "13px";
  document.querySelector(".price2").style.fontSize = "13px";
  document.querySelector(".price3").style.fontSize = "13px";
  document.querySelector(".price4").style.fontSize = "13px";
  document.querySelector(".price5").style.fontSize = "13px";
  document.querySelector(".price6").style.fontSize = "13px";
  document.querySelector(".dealtheme").style.fontSize = "16px";
  document.querySelector(".deal1").style.fontSize = "32px";
  document.querySelector(".dealp").style.fontSize = "16px";
  document.querySelector(".deala").style.fontSize = "11px";
  document.querySelector(".h3").style.fontSize = "28px";
  document.querySelector(".slick-next").style.fontSize = "16px";
  document.querySelector(".slick-prev ").style.fontSize = "16px";
  document.querySelector(".new1").style.fontSize = "10px";
  document.querySelector(".new2").style.fontSize = "10px";
  document.querySelector(".new3").style.fontSize = "10px";
  document.querySelector(".new4").style.fontSize = "10px";
  document.querySelector(".popular1").style.fontSize = "15px";
  document.querySelector(".popular2").style.fontSize = "15px";
  document.querySelector(".popular3").style.fontSize = "15px";
  document.querySelector(".popular4").style.fontSize = "15px";
  document.querySelector(".popular5").style.fontSize = "15px";
  document.querySelector(".popular6").style.fontSize = "15px";
  document.querySelector(".pop1").style.fontSize = "13px";
  document.querySelector(".pop2").style.fontSize = "13px";
  document.querySelector(".pop3").style.fontSize = "13px";
  document.querySelector(".pop4").style.fontSize = "13px";
  document.querySelector(".pop5").style.fontSize = "13px";
  document.querySelector(".pop6").style.fontSize = "13px";
  document.querySelector(".head1").style.fontSize = "20px";
  document.querySelector(".head2").style.fontSize = "20px";
  document.querySelector(".head3").style.fontSize = "20px";
  document.querySelector(".head4").style.fontSize = "20px";
  document.querySelector(".a1").style.fontSize = "16px";
  document.querySelector(".a2").style.fontSize = "16px";
  document.querySelector(".a3").style.fontSize = "16px";
  document.querySelector(".a4").style.fontSize = "16px";
  document.querySelector(".a5").style.fontSize = "16px";
  document.querySelector(".a6").style.fontSize = "16px";
  document.querySelector(".a7").style.fontSize = "16px";
  document.querySelector(".a8").style.fontSize = "16px";
  document.querySelector(".a9").style.fontSize = "16px";
  document.querySelector(".a10").style.fontSize = "16px";
  document.querySelector(".a11").style.fontSize = "16px";
  document.querySelector(".a12").style.fontSize = "16px";
  document.querySelector(".a13").style.fontSize = "16px";
  document.querySelector(".copy").style.fontSize = "16px";
}
function fontFunc4() {
  document.querySelector('.font-1').classList.remove("font-active");
  document.querySelector('.font-2').classList.remove("font-active");
  document.querySelector('.font-3').classList.remove("font-active");
  document.querySelector('.font-4').classList.add("font-active");
  document.querySelector('.font-5').classList.remove("font-active");
  document.querySelector(".nav-link1").style.fontSize = "12px" ;
  document.querySelector(".nav-link2").style.fontSize = "12px" ;
  document.querySelector(".nav-link3").style.fontSize = "12px" ;
  document.querySelector(".nav-link4").style.fontSize = "12px" ;
  document.querySelector(".nav-link5").style.fontSize = "12px" ;
  document.querySelector(".nav-link6").style.fontSize = "12px" ;
  document.querySelector(".nav-link7").style.fontSize = "12px" ;
  document.getElementById("slidename").style.fontSize = "54px";
  document.querySelector(".slide_2").style.fontSize = "54px";
  document.getElementById("button").style.fontSize = "12px";
  document.querySelector(".button_2").style.fontSize = "12px";
  document.querySelector(".icon1").style.fontSize= "28px";
  document.querySelector(".icon2").style.fontSize= "28px";
  document.querySelector(".icon3").style.fontSize= "28px";
  document.querySelector(".service-theme1").style.fontSize = "13px";
  document.querySelector(".service-theme2").style.fontSize = "13px";
  document.querySelector(".service-theme3").style.fontSize = "13px";
  document.querySelector(".service-p1").style.fontSize = "17px";
  document.querySelector(".service-p2").style.fontSize = "17px";
  document.querySelector(".service-p3").style.fontSize = "17px";
  document.querySelector(".sale1").style.fontSize = "11px";
  document.querySelector(".sale2").style.fontSize = "11px";
  document.querySelector(".sale3").style.fontSize = "11px";
  document.querySelector(".sale4").style.fontSize = "11px";
  document.querySelector(".ptheme1").style.fontSize = "16px";
  document.querySelector(".ptheme2").style.fontSize = "16px";
  document.querySelector(".ptheme3").style.fontSize = "16px";
  document.querySelector(".ptheme4").style.fontSize = "16px";
  document.querySelector(".ptheme5").style.fontSize = "16px";
  document.querySelector(".ptheme6").style.fontSize = "16px";
  document.querySelector(".price1").style.fontSize = "14px";
  document.querySelector(".price2").style.fontSize = "14px";
  document.querySelector(".price3").style.fontSize = "14px";
  document.querySelector(".price4").style.fontSize = "14px";
  document.querySelector(".price5").style.fontSize = "14px";
  document.querySelector(".price6").style.fontSize = "14px";
  document.querySelector(".dealtheme").style.fontSize = "17px";
  document.querySelector(".deal1").style.fontSize = "34px";
  document.querySelector(".dealp").style.fontSize = "17px";
  document.querySelector(".deala").style.fontSize = "12px";
  document.querySelector(".h3").style.fontSize = "29px";
  document.querySelector(".slick-next").style.fontSize = "17px";
  document.querySelector(".slick-prev ").style.fontSize = "17px";
  document.querySelector(".new1").style.fontSize = "11px";
  document.querySelector(".new2").style.fontSize = "11px";
  document.querySelector(".new3").style.fontSize = "11px";
  document.querySelector(".new4").style.fontSize = "11px";
  document.querySelector(".popular1").style.fontSize = "16px";
  document.querySelector(".popular2").style.fontSize = "16px";
  document.querySelector(".popular3").style.fontSize = "16px";
  document.querySelector(".popular4").style.fontSize = "16px";
  document.querySelector(".popular5").style.fontSize = "16px";
  document.querySelector(".popular6").style.fontSize = "16px";
  document.querySelector(".pop1").style.fontSize = "14px";
  document.querySelector(".pop2").style.fontSize = "14px";
  document.querySelector(".pop3").style.fontSize = "14px";
  document.querySelector(".pop4").style.fontSize = "14px";
  document.querySelector(".pop5").style.fontSize = "14px";
  document.querySelector(".pop6").style.fontSize = "14px";
  document.querySelector(".head1").style.fontSize = "21px";
  document.querySelector(".head2").style.fontSize = "21px";
  document.querySelector(".head3").style.fontSize = "21px";
  document.querySelector(".head4").style.fontSize = "21px";
  document.querySelector(".a1").style.fontSize = "17px";
  document.querySelector(".a2").style.fontSize = "17px";
  document.querySelector(".a3").style.fontSize = "17px";
  document.querySelector(".a4").style.fontSize = "17px";
  document.querySelector(".a5").style.fontSize = "17px";
  document.querySelector(".a6").style.fontSize = "17px";
  document.querySelector(".a7").style.fontSize = "17px";
  document.querySelector(".a8").style.fontSize = "17px";
  document.querySelector(".a9").style.fontSize = "17px";
  document.querySelector(".a10").style.fontSize = "17px";
  document.querySelector(".a11").style.fontSize = "17px";
  document.querySelector(".a12").style.fontSize = "17px";
  document.querySelector(".a13").style.fontSize = "17px";
  document.querySelector(".copy").style.fontSize = "17px";
}
function fontFunc5() {
  document.querySelector('.font-1').classList.remove("font-active");
  document.querySelector('.font-2').classList.remove("font-active");
  document.querySelector('.font-3').classList.remove("font-active");
  document.querySelector('.font-4').classList.remove("font-active");
  document.querySelector('.font-5').classList.add("font-active");
  document.querySelector(".nav-link1").style.fontSize = "13px" ;
  document.querySelector(".nav-link2").style.fontSize = "13px" ;
  document.querySelector(".nav-link3").style.fontSize = "13px" ;
  document.querySelector(".nav-link4").style.fontSize = "13px" ;
  document.querySelector(".nav-link5").style.fontSize = "13px" ;
  document.querySelector(".nav-link6").style.fontSize = "13px" ;
  document.querySelector(".nav-link7").style.fontSize = "13px" ;
  document.getElementById("slidename").style.fontSize = "58px";
  document.querySelector(".slide_2").style.fontSize = "58px";
  document.getElementById("button").style.fontSize = "13px";
  document.querySelector(".button_2").style.fontSize = "13px";
  document.querySelector(".icon1").style.fontSize= "31px";
  document.querySelector(".icon2").style.fontSize= "31px";
  document.querySelector(".icon3").style.fontSize= "31px";
  document.querySelector(".service-theme1").style.fontSize = "14px";
  document.querySelector(".service-theme2").style.fontSize = "14px";
  document.querySelector(".service-theme3").style.fontSize = "14px";
  document.querySelector(".service-p1").style.fontSize = "18px";
  document.querySelector(".service-p2").style.fontSize = "18px";
  document.querySelector(".service-p3").style.fontSize = "18px";
  document.querySelector(".sale1").style.fontSize = "12px";
  document.querySelector(".sale2").style.fontSize = "12px";
  document.querySelector(".sale3").style.fontSize = "12px";
  document.querySelector(".sale4").style.fontSize = "12px";
  document.querySelector(".ptheme1").style.fontSize = "17px";
  document.querySelector(".ptheme2").style.fontSize = "17px";
  document.querySelector(".ptheme3").style.fontSize = "17px";
  document.querySelector(".ptheme4").style.fontSize = "17px";
  document.querySelector(".ptheme5").style.fontSize = "17px";
  document.querySelector(".ptheme6").style.fontSize = "17px";
  document.querySelector(".price1").style.fontSize = "15px";
  document.querySelector(".price2").style.fontSize = "15px";
  document.querySelector(".price3").style.fontSize = "15px";
  document.querySelector(".price4").style.fontSize = "15px";
  document.querySelector(".price5").style.fontSize = "15px";
  document.querySelector(".price6").style.fontSize = "15px";
  document.querySelector(".dealtheme").style.fontSize = "18px";
  document.querySelector(".deal1").style.fontSize = "36px";
  document.querySelector(".dealp").style.fontSize = "18px";
  document.querySelector(".deala").style.fontSize = "13px";
  document.querySelector(".h3").style.fontSize = "30px";
  document.querySelector(".slick-next").style.fontSize = "18px";
  document.querySelector(".slick-prev ").style.fontSize = "18px";
  document.querySelector(".new1").style.fontSize = "12px";
  document.querySelector(".new2").style.fontSize = "12px";
  document.querySelector(".new3").style.fontSize = "12px";
  document.querySelector(".new4").style.fontSize = "12px";
  document.querySelector(".popular1").style.fontSize = "17px";
  document.querySelector(".popular2").style.fontSize = "17px";
  document.querySelector(".popular3").style.fontSize = "17px";
  document.querySelector(".popular4").style.fontSize = "17px";
  document.querySelector(".popular5").style.fontSize = "17px";
  document.querySelector(".popular6").style.fontSize = "17px";
  document.querySelector(".pop1").style.fontSize = "15px";
  document.querySelector(".pop2").style.fontSize = "15px";
  document.querySelector(".pop3").style.fontSize = "15px";
  document.querySelector(".pop4").style.fontSize = "15px";
  document.querySelector(".pop5").style.fontSize = "15px";
  document.querySelector(".pop6").style.fontSize = "15px";
  document.querySelector(".head1").style.fontSize = "22px";
  document.querySelector(".head2").style.fontSize = "22px";
  document.querySelector(".head3").style.fontSize = "22px";
  document.querySelector(".head4").style.fontSize = "22px";
  document.querySelector(".a1").style.fontSize = "18px";
  document.querySelector(".a2").style.fontSize = "18px";
  document.querySelector(".a3").style.fontSize = "18px";
  document.querySelector(".a4").style.fontSize = "18px";
  document.querySelector(".a5").style.fontSize = "18px";
  document.querySelector(".a6").style.fontSize = "18px";
  document.querySelector(".a7").style.fontSize = "18px";
  document.querySelector(".a8").style.fontSize = "18px";
  document.querySelector(".a9").style.fontSize = "18px";
  document.querySelector(".a10").style.fontSize = "18px";
  document.querySelector(".a11").style.fontSize = "18px";
  document.querySelector(".a12").style.fontSize = "18px";
  document.querySelector(".a13").style.fontSize = "18px";
  document.querySelector(".copy").style.fontSize = "18px";
}

function engFunc() {
  document.querySelector('.eng').classList.add("lan-active");
  document.querySelector('.rus').classList.remove("lan-active");
  document.querySelector('.uzb').classList.remove("lan-active");
  document.querySelector(".nav-link1").textContent = "new";
  document.querySelector(".nav-link2").textContent = "men";
  document.querySelector(".nav-link3").textContent = "women";
  document.querySelector(".nav-link4").textContent = "accessories";
  document.querySelector(".nav-link5").textContent = "jewelry";
  document.querySelector(".nav-link6").textContent = "about";
  document.querySelector(".nav-link7").textContent = "contact";
  document.querySelector(".navr-link1").textContent = "new";
  document.querySelector(".navr-link2").textContent = "men";
  document.querySelector(".navr-link3").textContent = "women";
  document.querySelector(".navr-link4").textContent = "accessories";
  document.querySelector(".navr-link5").textContent = "jewelry";
  document.querySelector(".navr-link6").textContent = "about";
  document.querySelector(".navr-link7").textContent = "contact";
  document.querySelector(".slide").innerHTML = "The New Way To Display <br> Product by <span>Colorib</span>";
  document.querySelector(".slide_2").innerHTML = "The New Way To Display <br> Product by <span>Colorib</span>";
  document.querySelector(".button").innerHTML = "EXPLORE NOW";
  document.querySelector(".button_2").innerHTML = "EXPLORE NOW";
  document.querySelector(".service-theme1").innerHTML ="WORLDWIDE DELIVERY";
  document.querySelector(".service-theme2").innerHTML ="SECURE PAYMENTS";
  document.querySelector(".service-theme3").innerHTML ="SIMPLE RETURNS";
  document.querySelector(".service-p1").innerHTML = "Far far away, behind the word mountains, far from the countries.";
  document.querySelector(".service-p2").innerHTML = "Far far away, behind the word mountains, far from the countries.";
  document.querySelector(".service-p3").innerHTML = "Far far away, behind the word mountains, far from the countries.";
  document.querySelector(".sale1").innerHTML = "new";
  document.querySelector(".sale2").innerHTML = "sale";
  document.querySelector(".sale3").innerHTML = "sale";
  document.querySelector(".sale4").innerHTML = "sale";
  document.querySelector(".ptheme1").innerHTML = "Kiko Linen Slip Dress, Brown";
  document.querySelector(".ptheme2").innerHTML = "Sleeve Dress, White";
  document.querySelector(".ptheme3").innerHTML = "Hodina Watch";
  document.querySelector(".ptheme4").innerHTML = "Kiko Linen Slip Dress, Brown";
  document.querySelector(".ptheme5").innerHTML = "Kid Dress, White";
  document.querySelector(".ptheme6").innerHTML = "Lady Shoes, Brown";
  document.querySelector(".dealtheme").innerHTML = "Limited Offers 20% OFF";
  document.querySelector(".deal1").innerHTML = "Week Deal";
  document.querySelector(".dealp").innerHTML = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum fuga incidunt laboriosam voluptas iure, delectus dignissimos facilis neque nulla earum.";
  document.querySelector(".deala").innerHTML = "shop now";
  document.querySelector(".h3").innerHTML = "Popular Items";
  document.querySelector(".slick-next").innerHTML = "Next";
  document.querySelector(".slick-prev").innerHTML = "Previous";
  document.querySelector(".slick-prev").style.right = "100px";
  document.querySelector(".new1").innerHTML = "new";
  document.querySelector(".new2").innerHTML = "sale";
  document.querySelector(".new3").innerHTML = "sale";
  document.querySelector(".new4").innerHTML = "sale";
  document.querySelector(".popular1").innerHTML = "Kiko Linen Slip Dress, Brown";
  document.querySelector(".popular2").innerHTML = "Sleeve Dress, White";
  document.querySelector(".popular3").innerHTML = "Hodina Watch";
  document.querySelector(".popular4").innerHTML = "Kiko Linen Slip Dress, Brown";
  document.querySelector(".popular5").innerHTML = "Kid Dress, White";
  document.querySelector(".popular6").innerHTML = "Lady Shoes, Brown";
  document.querySelector(".head1").innerHTML = "Help";
  document.querySelector(".head2").innerHTML = "About";
  document.querySelector(".head3").innerHTML = "Shop";
  document.querySelector(".head4").innerHTML = "Join our list and receive exclusives";
  document.querySelector(".a1").innerHTML = "Contact us";
  document.querySelector(".a2").innerHTML = "Account";
  document.querySelector(".a3").innerHTML = "Shipping";
  document.querySelector(".a4").innerHTML = "Returns";
  document.querySelector(".a5").innerHTML = "FAQ";
  document.querySelector(".a6").innerHTML = "About us";
  document.querySelector(".a7").innerHTML = "Press";
  document.querySelector(".a8").innerHTML = "Careers";
  document.querySelector(".a9").innerHTML = "Team";
  document.querySelector(".a10").innerHTML = "FAQ";
  document.querySelector(".a11").innerHTML = "Store";
  document.querySelector(".a12").innerHTML = "Gift Cards";
  document.querySelector(".a13").innerHTML = "Student Discount";
  document.querySelector(".but").innerHTML = "subscribe";
  document.querySelector(".copy").innerHTML = "Copyright ©2020 All rights reserved | This template is made with  by Colorlib";
  document.querySelector(".set").innerHTML = "Settings";
  document.querySelector(".lan").innerHTML = "Language";
}
function rusFunc() {
  document.querySelector('.eng').classList.remove("lan-active");
  document.querySelector('.rus').classList.add("lan-active");
  document.querySelector('.uzb').classList.remove("lan-active");
  document.querySelector(".nav-link1").textContent = "новый";
  document.querySelector(".nav-link2").textContent = "мужчины";
  document.querySelector(".nav-link3").textContent = "женщины";
  document.querySelector(".nav-link4").textContent = "аксессуары";
  document.querySelector(".nav-link5").textContent = "Ювелир";
  document.querySelector(".nav-link6").textContent = "o";
  document.querySelector(".nav-link7").textContent = "контакт";
  document.querySelector(".navr-link1").textContent = "новый";
  document.querySelector(".navr-link2").textContent = "мужчины";
  document.querySelector(".navr-link3").textContent = "женщины";
  document.querySelector(".navr-link4").textContent = "аксессуары";
  document.querySelector(".navr-link5").textContent = "Ювелир";
  document.querySelector(".navr-link6").textContent = "o";
  document.querySelector(".navr-link7").textContent = "контакт";
  document.querySelector(".slide").innerHTML = "Новый способ отображения <br> Продукт от <span>Colorib</span>";
  document.querySelector(".slide_2").innerHTML = "Новый способ отображения <br> Продукт от <span>Colorib</span>";
  document.querySelector(".button").innerHTML = "УЗНАТЬ СЕЙЧАС";
  document.querySelector(".button_2").innerHTML = "УЗНАТЬ СЕЙЧАС";
  document.querySelector(".service-theme1").innerHTML ="ДОСТАВКА ПО ВСЕМУ МИРУ";
  document.querySelector(".service-theme2").innerHTML ="БЕЗОПАСНЫЕ ПЛАТЕЖИ";
  document.querySelector(".service-theme3").innerHTML ="ПРОСТОЙ ВОЗВРАТ";
  document.querySelector(".service-p1").innerHTML = "Далеко-далеко, за словами горы, далеко от страны.";
  document.querySelector(".service-p2").innerHTML = "Далеко-далеко, за словами горы, далеко от страны.";
  document.querySelector(".service-p3").innerHTML = "Далеко-далеко, за словами горы, далеко от страны.";
  document.querySelector(".sale1").innerHTML = "новый";
  document.querySelector(".sale2").innerHTML = "продажа";
  document.querySelector(".sale3").innerHTML = "продажа";
  document.querySelector(".sale4").innerHTML = "продажа";
  document.querySelector(".ptheme1").innerHTML = "Платье-комбинация из льна Kiko, коричневое";
  document.querySelector(".ptheme2").innerHTML = "Платье с рукавами, белое";
  document.querySelector(".ptheme3").innerHTML = "Часы Hodina";
  document.querySelector(".ptheme4").innerHTML = "Платье-комбинация из льна Kiko, коричневое";
  document.querySelector(".ptheme5").innerHTML = "Детское платье, белое";
  document.querySelector(".ptheme6").innerHTML = "Леди Обувь, Коричневый";
  document.querySelector(".dealtheme").innerHTML = "Ограниченные предложения СКИДКА 20%";
  document.querySelector(".deal1").innerHTML = "Недельная сделка";
  document.querySelector(".dealp").innerHTML = "В нем упрощена организация совместной работы и добавлен функционал, позволяющий ускорить выполнение большинства рутинных задач.";
  document.querySelector(".deala").innerHTML = "купить сейчас";
  document.querySelector(".h3").innerHTML = "Популярные товары";
  document.querySelector(".slick-next").innerHTML = "Cледующий";
  document.querySelector(".slick-prev").innerHTML = "Предыдущий";
  document.querySelector(".slick-prev").style.right = "150px";
  document.querySelector(".new1").innerHTML = "новый";
  document.querySelector(".new2").innerHTML = "продажа";
  document.querySelector(".new3").innerHTML = "продажа";
  document.querySelector(".new4").innerHTML = "продажа";
  document.querySelector(".popular1").innerHTML = "Платье-комбинация из льна Kiko, коричневое";
  document.querySelector(".popular2").innerHTML = "Платье с рукавами, белое";
  document.querySelector(".popular3").innerHTML = "Часы Hodina";
  document.querySelector(".popular4").innerHTML = "Платье-комбинация из льна Kiko, коричневое";
  document.querySelector(".popular5").innerHTML = "Детское платье, белое";
  document.querySelector(".popular6").innerHTML = "Леди Обувь, Коричневый";
  document.querySelector(".head1").innerHTML = "Помощ";
  document.querySelector(".head2").innerHTML = "O";
  document.querySelector(".head3").innerHTML = "Магазин";
  document.querySelector(".head4").innerHTML = "Присоединяйтесь к нашему списку и получайте эксклюзивы";
  document.querySelector(".a1").innerHTML = "Свяжитесь с нами";
  document.querySelector(".a2").innerHTML = "Счет";
  document.querySelector(".a3").innerHTML = "Перевозка";
  document.querySelector(".a4").innerHTML = "Returns";
  document.querySelector(".a5").innerHTML = "Возврат";
  document.querySelector(".a6").innerHTML = "О нас";
  document.querySelector(".a7").innerHTML = "Нажмите";
  document.querySelector(".a8").innerHTML = "Карьера";
  document.querySelector(".a9").innerHTML = "Команда";
  document.querySelector(".a10").innerHTML = "ЧЗВ";
  document.querySelector(".a11").innerHTML = "хранить";
  document.querySelector(".a12").innerHTML = "Подарочные карты";
  document.querySelector(".a13").innerHTML = "Студенческая скидка";
  document.querySelector(".but").innerHTML = "подписываться";
  document.querySelector(".copy").innerHTML = "Copyright © 2020 Все права защищены | Этот шаблон создан с помощью Colorlib";
  document.querySelector(".set").innerHTML = "Настройки";
  document.querySelector(".lan").innerHTML = "Язык";
}
function uzbFunc() {
  document.querySelector('.eng').classList.remove("lan-active");
  document.querySelector('.rus').classList.remove("lan-active");
  document.querySelector('.uzb').classList.add("lan-active");
  document.querySelector(".nav-link1").textContent = "yange";
  document.querySelector(".nav-link2").textContent = "erkak";
  document.querySelector(".nav-link3").textContent = "ayol";
  document.querySelector(".nav-link4").textContent = "aksessuar";
  document.querySelector(".nav-link5").textContent = "taqinchoq";
  document.querySelector(".nav-link6").textContent = "haqida";
  document.querySelector(".nav-link7").textContent = "aloqa";
  document.querySelector(".navr-link1").textContent = "yange";
  document.querySelector(".navr-link2").textContent = "erkak";
  document.querySelector(".navr-link3").textContent = "ayol";
  document.querySelector(".navr-link4").textContent = "aksessuar";
  document.querySelector(".navr-link5").textContent = "taqinchoq";
  document.querySelector(".navr-link6").textContent = "haqida";
  document.querySelector(".navr-link7").textContent = "aloqa";
  document.querySelector(".slide").innerHTML = "Ko'rsatishning yangi usuli <span>Colorib</span> <br> tomonidan ishlab chiqarilgan mahsulot";
  document.querySelector(".slide_2").innerHTML = "Ko'rsatishning yangi usuli <span>Colorib</span> <br> tomonidan ishlab chiqarilgan mahsulot";
  document.querySelector(".button").innerHTML = "Hoziroq ulaning";
  document.querySelector(".button_2").innerHTML = "Hoziroq ulaning"
  document.querySelector(".service-theme1").innerHTML ="Dunyo bo'ylab yetkazib berish";
  document.querySelector(".service-theme2").innerHTML ="Xavfsiz to'lash";
  document.querySelector(".service-theme3").innerHTML ="Oddiy qaytish";
  document.querySelector(".service-p1").innerHTML = "Uzoqda, tog'lar so'zining orqasida, mamlakatlardan uzoqda.";
  document.querySelector(".service-p2").innerHTML = "Uzoqda, tog'lar so'zining orqasida, mamlakatlardan uzoqda.";
  document.querySelector(".service-p3").innerHTML = "Uzoqda, tog'lar so'zining orqasida, mamlakatlardan uzoqda.";
  document.querySelector(".sale1").innerHTML = "yangi";
  document.querySelector(".sale2").innerHTML = "chegirma";
  document.querySelector(".sale3").innerHTML = "chegirma";
  document.querySelector(".sale4").innerHTML = "chegirma";
  document.querySelector(".ptheme1").innerHTML = "Kiko choyshabidan tikilgan kiyim, jigarrang";
  document.querySelector(".ptheme2").innerHTML = "Yeng kiyimi, oq rang";
  document.querySelector(".ptheme3").innerHTML = "Hodina tomoshasi";
  document.querySelector(".ptheme4").innerHTML = "Kiko choyshabidan tikilgan kiyim, jigarrang";
  document.querySelector(".ptheme5").innerHTML = "Bolalar kiyimi, oq";
  document.querySelector(".ptheme6").innerHTML = "Lady Shoes, jigarrang";
  document.querySelector(".dealtheme").innerHTML = "Cheklangan takliflar 20% chegirma";
  document.querySelector(".deal1").innerHTML = "Haftalik bitim";
  document.querySelector(".dealp").innerHTML = "Bizga ma`lumki , til kishilar orasida eng muhim aloqa vositasi bo‘lib xizmat qiladi . Tilda fikr ifodalash , bayon qilish va anglashda esa gapdan foydalaniladi . Demak , gap , avvalo , tinglovchi uchun esafikr anglash vositasidir.";
  document.querySelector(".deala").innerHTML = "xarid qilish";
  document.querySelector(".h3").innerHTML = "Mashxur mahsulotlar";
  document.querySelector(".slick-next").innerHTML = "Keyingi";
  document.querySelector(".slick-prev").innerHTML = "Oldingi";
  document.querySelector(".slick-prev").style.right = "100px";
  document.querySelector(".new1").innerHTML = "yangi";
  document.querySelector(".new2").innerHTML = "chegirma";
  document.querySelector(".new3").innerHTML = "chegirma";
  document.querySelector(".new4").innerHTML = "chegirma";
  document.querySelector(".popular1").innerHTML = "Kiko choyshabidan tikilgan kiyim, jigarrang";
  document.querySelector(".popular2").innerHTML = "Yeng kiyimi, oq rang";
  document.querySelector(".popular3").innerHTML = "Hodina tomoshasi";
  document.querySelector(".popular4").innerHTML = "Kiko choyshabidan tikilgan kiyim, jigarrang";
  document.querySelector(".popular5").innerHTML = "Bolalar kiyimi, oq";
  document.querySelector(".popular6").innerHTML = "Lady Shoes, jigarrang";
  document.querySelector(".head1").innerHTML = "Yordam";
  document.querySelector(".head2").innerHTML = "Haqida";
  document.querySelector(".head3").innerHTML = "Do'kon";
  document.querySelector(".head4").innerHTML = "Bizning ro'yxatimizga qo'shiling va eksklyuzivlar oling";
  document.querySelector(".a1").innerHTML = "Biz bilan bog'lanish";
  document.querySelector(".a2").innerHTML = "Account";
  document.querySelector(".a3").innerHTML = "Hisob qaydnomasi";
  document.querySelector(".a4").innerHTML = "Returns";
  document.querySelector(".a5").innerHTML = "Qaytish";
  document.querySelector(".a6").innerHTML = "Biz haqimizda";
  document.querySelector(".a7").innerHTML = "Matbuot";
  document.querySelector(".a8").innerHTML = "Karyera";
  document.querySelector(".a9").innerHTML = "Jamoa";
  document.querySelector(".a10").innerHTML = "FAQ";
  document.querySelector(".a11").innerHTML = "Do'kon";
  document.querySelector(".a12").innerHTML = "Sovg'a kartalari";
  document.querySelector(".a13").innerHTML = "Talaba chegirmasi";
  document.querySelector(".but").innerHTML = "obuna bo'lish";
  document.querySelector(".copy").innerHTML = "© 2020 Barcha huquqlar himoyalangan | Ushbu shablon Colorlib tomonidan tayyorlangan";
  document.querySelector(".set").innerHTML = "Sozlamalar";
  document.querySelector(".lan").innerHTML = "Tillar";
}



